### ISSUE TITLE
Move to Eclipse

### ISSUE THREAD

**Issue by keilw** [eclipse/jnosql-artemis#21]
When is this repository supposed to move under the Eclipse organization?

**Comment by keilw** [comment]
@otaviojava Why did you close this, does it mean, Artemis should never move to Eclipse?

**Comment by otaviojava** [comment]
That is WIP by Eclipse Legal team and not to us.

**Comment by keilw** [comment]
Still unclear why parallel IP could not work here?

**Comment by otaviojava** [comment]
Ok, we can keep it here.

**Comment by otaviojava** [comment]
Done.
