### ISSUE TITLE
Fixes list with embedded elements

### ISSUE THREAD

**Issue by DaniloAndrade** [eclipse/jnosql-artemis#31]
I have the following scenario:

```java
@Embeddable
public class Contato {

	@Column
	private TipoContato tipo;
	@Column
	private String informacao;
     
       //Getters/Setters
	
}

public enum TipoContato {
	TELEFONE,CELULAR,EMAIL
}


@Entity("users")
public class Usuario {

	@Id
	private String id;
	@Column
	private String nome;
	@Column
	private String sobrenome;
	@Column
	private List<Contato> contatos = new ArrayList<>();

	//Getters/Setters
}

```
when trying to save the following exception run:

> Caused by: org.bson.codecs.configuration.CodecConfigurationException: Can't find a codec for class br.xpto.Contato.
> 	at org.bson.codecs.configuration.CodecCache.getOrThrow(CodecCache.java:46)
> 	at org.bson.codecs.configuration.ProvidersCodecRegistry.get(ProvidersCodecRegistry.java:63)
> 	at org.bson.codecs.configuration.ChildCodecRegistry.get(ChildCodecRegistry.java:51)
> 	at org.bson.codecs.DocumentCodec.writeValue(DocumentCodec.java:174)
> 	at org.bson.codecs.DocumentCodec.writeIterable(DocumentCodec.java:197)
> 	at org.bson.codecs.DocumentCodec.writeValue(DocumentCodec.java:170)
> 	at org.bson.codecs.DocumentCodec.writeMap(DocumentCodec.java:189)
> 	at org.bson.codecs.DocumentCodec.encode(DocumentCodec.java:131)
> 	at org.bson.codecs.DocumentCodec.encode(DocumentCodec.java:45)
> 	at org.bson.codecs.BsonDocumentWrapperCodec.encode(BsonDocumentWrapperCodec.java:63)
> 	at org.bson.codecs.BsonDocumentWrapperCodec.encode(BsonDocumentWrapperCodec.java:29)
> 	at com.mongodb.connection.InsertCommandMessage.writeTheWrites(InsertCommandMessage.java:101)
> 	at com.mongodb.connection.InsertCommandMessage.writeTheWrites(InsertCommandMessage.java:43)
> 	at com.mongodb.connection.BaseWriteCommandMessage.encodeMessageBodyWithMetadata(BaseWriteCommandMessage.java:129)
> 	at com.mongodb.connection.RequestMessage.encodeWithMetadata(RequestMessage.java:160)
> 	at com.mongodb.connection.WriteCommandProtocol.sendMessage(WriteCommandProtocol.java:220)
> 	at com.mongodb.connection.WriteCommandProtocol.execute(WriteCommandProtocol.java:101)
> 	at com.mongodb.connection.InsertCommandProtocol.execute(InsertCommandProtocol.java:67)
> 	at com.mongodb.connection.InsertCommandProtocol.execute(InsertCommandProtocol.java:37)
> 	at com.mongodb.connection.DefaultServer$DefaultServerProtocolExecutor.execute(DefaultServer.java:168)
> 	at com.mongodb.connection.DefaultServerConnection.executeProtocol(DefaultServerConnection.java:289)
> 	at com.mongodb.connection.DefaultServerConnection.insertCommand(DefaultServerConnection.java:118)
> 	at com.mongodb.operation.MixedBulkWriteOperation$Run$2.executeWriteCommandProtocol(MixedBulkWriteOperation.java:465)
> 	at com.mongodb.operation.MixedBulkWriteOperation$Run$RunExecutor.execute(MixedBulkWriteOperation.java:656)
> 	at com.mongodb.operation.MixedBulkWriteOperation$Run.execute(MixedBulkWriteOperation.java:411)
> 	at com.mongodb.operation.MixedBulkWriteOperation$1.call(MixedBulkWriteOperation.java:177)
> 	at com.mongodb.operation.MixedBulkWriteOperation$1.call(MixedBulkWriteOperation.java:168)
> 	at com.mongodb.operation.OperationHelper.withConnectionSource(OperationHelper.java:422)
> 	at com.mongodb.operation.OperationHelper.withConnection(OperationHelper.java:413)
> 	at com.mongodb.operation.MixedBulkWriteOperation.execute(MixedBulkWriteOperation.java:168)
> 	at com.mongodb.operation.MixedBulkWriteOperation.execute(MixedBulkWriteOperation.java:74)
> 	at com.mongodb.Mongo.execute(Mongo.java:845)
> 	at com.mongodb.Mongo$2.execute(Mongo.java:828)
> 	at com.mongodb.MongoCollectionImpl.executeSingleWriteRequest(MongoCollectionImpl.java:550)
> 	at com.mongodb.MongoCollectionImpl.insertOne(MongoCollectionImpl.java:317)
> 	at com.mongodb.MongoCollectionImpl.insertOne(MongoCollectionImpl.java:307)
> 	at org.jnosql.diana.mongodb.document.MongoDBDocumentCollectionManager.insert(MongoDBDocumentCollectionManager.java:62)
> 	at org.jnosql.artemis.document.AbstractDocumentTemplate.lambda$insert$0(AbstractDocumentTemplate.java:48)
> 	at java.util.function.Function.lambda$andThen$1(Function.java:88)
> 	at java.util.function.Function.lambda$andThen$1(Function.java:88)
> 	at java.util.function.Function.lambda$andThen$1(Function.java:88)
> 	at java.util.function.Function.lambda$andThen$1(Function.java:88)
> 	at java.util.function.Function.lambda$andThen$1(Function.java:88)
> 	at org.jnosql.artemis.document.DefaultDocumentWorkflow.flow(DefaultDocumentWorkflow.java:48)
> 	at org.jnosql.artemis.document.AbstractDocumentTemplate.insert(AbstractDocumentTemplate.java:49)
> 	at org.jnosql.artemis.document.query.AbstractDocumentRepository.save(AbstractDocumentRepository.java:60)
> 	... 56 more
> 

**I tested it on version 0.0.3**

**Comment by otaviojava** [comment]
Hey, @DaniloAndrade thank you for report this error, I'm working on this issue.

**Comment by otaviojava** [comment]
Fixed.
That will be ready in the next version.
Thanks for the feedback.
