### ISSUE TITLE
Have specific annotations to Entity

### ISSUE THREAD

**Issue by otaviojava** [eclipse/jnosql-artemis#41]
The goal of this issue is to allow specific domain entity to each NoSQL type. To solve this problem, I saw two options:

## 1 Allow the ```@Entity``` be extensible

Allows the ```@Entity``` be used in the other Annotation. Once this annotation applies the Entity, it has the same property of this Entity annotation.

```java
@Retention(RetentionPolicy.RUNTIME)
@Target(ElementType.TYPE)
@Stereotype
@Entity
public @interface CustomAnnotation {
    /**
     * The name of an entity. Defaults to the unqualified name of the entity class.
     * @return the entity name (Optional)
     */
    String value() default "";
}

```

```java
@CustomAnnotation
public class Person {
//fields
}
```

So, will be an alias to:

```java
@Entity
public class Person {
//fields
}
```

### Conditions:

* When there are two annotations that will use the Entity one.
* Where there are two custom annotations then can use anyone.
* When the custom annotation doesn't have a ```String value() default "";``` it will use the [Class.getSimpleName()](https://docs.oracle.com/javase/8/docs/api/java/lang/Class.html#getSimpleName--)
* Where there is the method, that must use the same rule of the Entity

### Adds four custom annotations kinds

* ColumnFamily in the  column API
* DocumentCollection in the  document API
* Bucket in the  key-value API
* Vertex in the  graph API

## 2 Add new annotations

Just add new annotations:

* ColumnFamily in the  column API
* DocumentCollection in the  document API
* Bucket in the  key-value API
* Vertex in the  graph API

## 3 keep what we have

The DDD fundamentals say:

> An entity is an object fundamentally defined not by its attributes, but by a thread of continuity and identity.

Thereby, the concept is technology agnostic

**Comment by Hilmerc** [comment]
JPA has `@ Entity`, my suggestion is not to use the same name for NoSQL annotations, is it possible to change` org.jnosql.artemis.Entity` for something like `org.jnosql.artemis.Vertex` to avoid confuses?

**Comment by otaviojava** [comment]
IMHO, that is already a good name and agnostic from any technology, let's see what the others think about this.

**Comment by jesse-gallagher** [comment]
I like @Entity as the base annotation name for agnosticism purposes as well - @Vertex would make sense for graph implementations, but would be counter-intuitive for other DBs. It’d make sense to use as the domain-specific extended one as in the issue body, though.

**Comment by furlaneto** [comment]
I think **@Entity** is a good name and could be extensible. @Vertex would be nice for graph, but wouldn`t make sense to others dbs.

**Comment by vertex** [comment]
I am pretty cross domain, thank you very much.
