### ISSUE TITLE
how to bootstrap using java ee?

### ISSUE THREAD

**Issue by asafbennatan** [eclipse/jnosql-artemis#52]
am able to start diana , but when trying to inject a repoistory i get;

Unsatisfied dependencies for type NoSqlJNOSQLRepository with qualifiers @Database
  at injection point [BackedAnnotatedField] @Inject @Database private com.xxx.init.Initializator.noSqlRepository

injection point:

 @Inject
    @Database(DatabaseType.DOCUMENT)
    private NoSqlJNOSQLRepository noSqlRepository;

**Comment by otaviojava** [comment]
Hello, how is going?
First, you need to make a DocumentCollection to CDI container

```java
@ApplicationScoped
public class MongoDBProducer {

    private static final String COLLECTION = "developers";

    private MongoDBDocumentConfiguration configuration;

    private DocumentCollectionManagerFactory managerFactory;

    @PostConstruct
    public void init() {
        configuration = new MongoDBDocumentConfiguration();
        managerFactory = configuration.get();
    }


    @Produces
    public DocumentCollectionManager getManager() {
        return managerFactory.get(COLLECTION);

    }

}
```

Here same codes samples:

* https://github.com/JNOSQL/artemis-demo
* https://github.com/Adopt-a-JSR/MVC1.0.Ozark

Here, we have several samples using Artemis with CDI 2.0:
* https://github.com/JNOSQL/artemis-demo

**Comment by asafbennatan** [comment]
Hi , thanks for the quick response.
i am doing that already with this class:

`@ApplicationScoped
public class NoSqlJNOSQLProvider {
    private static final String COLLECTION = "dbNoSQL";

    private DocumentConfiguration configuration;

    private DocumentCollectionManagerFactory managerFactory;

    @PostConstruct
    public void init() {
        configuration = new MongoDBDocumentConfiguration();
        managerFactory = configuration.get();
    }


    @Produces
    public DocumentCollectionManager getManager() {
        return managerFactory.get(COLLECTION);

    }

}`

injecting DocumentCollectionManager and executing something like this:

`
 DocumentEntity testNoSQl1 = DocumentEntity.of("TestNoSQl");
        testNoSQl1.add(Document.of("dummy","asaf"));
        quaryEnabler.insert(testNoSQl1);
`

works.


but injecting custom repository does not work and the error is the one given above

Thanks.

**Comment by otaviojava** [comment]
That seems the CDI cannot find the bean.
Did you set the bean.xml?
https://github.com/JNOSQL/artemis-demo/blob/master/artemis-demo-java-se/cassandra/src/main/resources/META-INF/beans.xml

Do you have this code on GitHub? Could you share the link?

**Comment by asafbennatan** [comment]
Hi, 
i placed beans.xml but still no luck . what is the class for this bean i will try register it programmatically some how.
i am using wildfly with an ear deploymnet structure (war inside)

**Comment by keilw** [comment]
Even if it's just an example code, shouldn't it be `JNoSQLRepository` instead of `NoSQLJRepository`?

**Comment by otaviojava** [comment]
@keilw the name does not matter on this case

**Comment by otaviojava** [comment]
@asafbennatan 
do you mind to put this sample code on a GitHub repository?
So, we can go more in-depth on that together.

**Comment by asafbennatan** [comment]
where ? , i dont have any class name `JNoSQLRepository` or are you just commenting about the class name ?

**Comment by asafbennatan** [comment]
@otaviojava i will have to create a sample project first

**Comment by asafbennatan** [comment]
here it is:

https://github.com/asafbennatan/jnosqlTest

**Comment by otaviojava** [comment]
Thank you, I'll take a look

**Comment by otaviojava** [comment]
Could you try with Java SE 8, please?
it's working on my machine

**Comment by asafbennatan** [comment]
Hi, i am sure it qill work on se, im trying to get to work on ee

**Comment by asafbennatan** [comment]
If you know the beans class i can try to manually register it with the
application server

**Comment by otaviojava** [comment]
@asafbennatan 
Could you provide your full log, please?
I need this log information:
https://github.com/eclipse/jnosql-artemis/blob/master/artemis-document/src/main/java/org/jnosql/artemis/document/spi/DocumentCollectionProducerExtension.java#L96

**Comment by asafbennatan** [comment]
In a meeting will try to send the log asap, btw if im not mistaken in order
to register an extension in java ee you have to add an descrptor file

**Comment by otaviojava** [comment]
Yes, we did it:
https://github.com/eclipse/jnosql-artemis/blob/master/artemis-document/src/main/resources/META-INF/services/javax.enterprise.inject.spi.Extension

**Comment by asafbennatan** [comment]
[log.txt](https://github.com/eclipse/jnosql-artemis/files/2045925/log.txt)

**Comment by otaviojava** [comment]
it seems the server is not starting the extension.
That is weird, because. 
Do you know if ear file has support to CDI extension?

I'll check this.

**Comment by asafbennatan** [comment]
Hi, this is actually being deployed as a war.
Wars do have support for extensions, preheps i should place the extension
description directly under the war

**Comment by otaviojava** [comment]
Weird...
Could you try this one?
https://github.com/JNOSQL/artemis-demo
that is just a '.war'

**Comment by asafbennatan** [comment]
Hi ,
have cloned the repository, how can i create a war out of it ? seems like
the only goal there is jar , or am i missing something?

2018-05-29 0:28 GMT+03:00 Otávio Santana <notifications@github.com>:

**Comment by asafbennatan** [comment]
Hi,
found the issue  , forgot to add the Artemis-document dependency ,
found it as i was trying to found the class you have sent earlier ,
sorry about that ,
Thanks for your help!

2018-05-29 0:51 GMT+03:00 asaf bennatan <asafbennatan@gmail.com>:

**Comment by otaviojava** [comment]
Glad to hear that.
That was my pleasure.
You welcome, if you have more questions, please, let me know.
