### ISSUE TITLE
query dates

### ISSUE THREAD

**Issue by asafbennatan** [eclipse/jnosql-artemis#54]
hi , 
i have seen that we can persist entities with date fields,
how can we use DocumentQueryMapperBuilder to create a query using date ?
something like:
`documentTemplate.select(mapperBuilder.selectFrom(Person.class).where("date").between(start,end)....
`
where start and end are dates and not long

**Comment by otaviojava** [comment]
we don't have it yet, but that is something that we need to improve to the next version.

**Comment by otaviojava** [comment]
Thanks, we already fixed these PRs.
We have the plan to release in June with these fixes included.
